export const LOCATION_MODES = {
  FREE_ONLY: "FREE_ONLY",
  VIRTUAL_ONLY: "VIRTUAL_ONLY",
  HYBRID: "HYBRID"
};

export const RESOLVED_AS = {
  FIXED_STOP: "FIXED_STOP",
  FREE_POINT: "FREE_POINT",
  VIRTUAL_STOP: "VIRTUAL_STOP"
};

export const CHANNELS = {
  PASSENGER_APP: "PASSENGER_APP",
  DISPATCHER_WEB: "DISPATCHER_WEB",
  PHONE_IVR: "PHONE_IVR",
  PHONE_OPERATOR: "PHONE_OPERATOR"
};

export const ADAPTER_TYPES = {
  WEBHOOK: "WEBHOOK",
  SIP: "SIP",
  CTI: "CTI",
  SERIAL_COM: "SERIAL_COM"
};
